name: 🐛 Bug Report
description: 버그를 보고하는 템플릿
title: "[Bug] "
labels:
  - 🐛 bug
body:
  - type: markdown
    attributes:
      value: |
        ## 버그 리포트
        버그를 보고해 주셔서 감사합니다. 아래 정보를 작성해 주시면 문제 해결에 도움이 됩니다.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: 사전 확인사항
      description: 이슈를 제출하기 전에 아래 항목을 확인해주세요
      options:
        - label: 동일한 버그에 대한 이슈가 이미 존재하는지
          required: true
        - label: 최신 버전을 사용하고 있는지
          required: true

  - type: textarea
    id: environment
    attributes:
      label: 환경 정보
      description: 버그가 발생한 환경에 대한 정보를 제공해주세요
      placeholder: |
        - OS: [예: Windows 10, macOS 12.0, Ubuntu 20.04]
        - 브라우저: [예: Chrome 96, Safari 15, Firefox 94]
        - 버전: [예: v1.2.3]
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: 현재 동작
      description: 발생한 버그에 대해 명확하고 간결하게 설명해주세요
      placeholder: 어떤 문제가 발생했는지 설명해주세요
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 예상 동작
      description: 예상했던 정상적인 동작을 설명해주세요
      placeholder: 원래 어떻게 동작해야 했는지 설명해주세요
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 재현 단계
      description: 버그를 재현하는 단계를 설명해주세요
      placeholder: |
        1. '...' 페이지로 이동
        2. '...' 버튼 클릭
        3. '...' 입력
        4. 오류 발생
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 관련 로그 및 스크린샷
      description: 관련된 로그 출력이나 스크린샷을 첨부해주세요
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: 추가 정보
      description: 문제 해결에 도움이 될 수 있는 추가 정보를 제공해주세요
