name: 🧹 Chore
description: 프로젝트 유지보수 작업을 위한 템플릿
title: "[Chore] "
labels:
  - 🧹 chore
body:
  - type: markdown
    attributes:
      value: |
        ## 유지보수 작업
        프로젝트 유지보수 작업에 대한 정보를 작성해주세요.

  - type: textarea
    id: motivation
    attributes:
      label: 작업 동기
      description: 이 작업이 필요한 이유를 설명해주세요
      placeholder: 왜 이 작업이 필요한지 설명해주세요
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 작업 목록
      description: 수행할 작업 목록을 체크리스트 형식으로 작성해주세요
      placeholder: |
        - [ ] 종속성 업데이트
        - [ ] 설정 파일 수정
        - [ ] 코드 정리
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 추가 정보
      description: 작업에 도움이 될 수 있는 추가 정보를 제공해주세요
