name: 📝 Documentation
description: 문서 작성 또는 수정을 위한 템플릿
title: "[Docs] "
labels:
  - 📝 documentation
body:
  - type: markdown
    attributes:
      value: |
        ## 문서 작업
        문서 작성 또는 수정에 대한 정보를 작성해주세요.

  - type: dropdown
    id: doc-type
    attributes:
      label: 문서 유형
      description: 작업할 문서의 유형을 선택해주세요
      options:
        - README
        - API 문서
        - 사용자 가이드
        - 개발자 가이드
        - 코드 주석
        - 기타 (아래 설명에 상세히 작성해주세요)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 작업 설명
      description: 문서 작업에 대해 설명해주세요
      placeholder: 어떤 문서를 작성하거나 수정할 예정인지 설명해주세요
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 작업 목록
      description: 수행할 문서 작업 목록을 체크리스트 형식으로 작성해주세요
      placeholder: |
        - [ ] 초안 작성
        - [ ] 리뷰 요청
        - [ ] 피드백 반영
        - [ ] 최종 문서 작성

  - type: textarea
    id: additional-context
    attributes:
      label: 추가 정보
      description: 문서 작업에 도움이 될 수 있는 추가 정보를 제공해주세요
