name: ✨ Feature
description: 새로운 기능을 구현하거나 기존 기능을 수정을 위한 템플릿
title: "[FEATURE] "
labels: 
  - ✨ feature
body:
  - type: markdown
    attributes:
      value: |
        ## 기능 제안
        새로운 기능을 제안해 주셔서 감사합니다. 아래 정보를 작성해 주시면 검토에 도움이 됩니다.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: 사전 확인사항
      description: 이슈를 제출하기 전에 아래 항목을 확인해주세요
      options:
        - label: 동일한 기능 제안이 이미 존재하는지 
          required: true
        - label: 이 기능이 프로젝트의 목표와 일치하는지 
          required: true
    
  - type: textarea
    id: task-description
    attributes:
      label: 📄 작업 설명
      description: 무슨 작업을 할 계획인지 간단하게 설명해주세요.
      placeholder: ex) ~를 위해 ~기능을 구현합니다.
    validations:
      required: true

  - type: textarea
    id: task-steps
    attributes:
      label: 📈 진행 체크리스트
      description: 어떤 작업을 진행할지 체크리스트 형식으로 작성해주세요. (선택 사항)
      placeholder: |
        - [ ] 작업 1
        - [ ] 작업 2

  - type: textarea
    id: additional-context
    attributes:
      label: 👍🏻 추가 정보
      description: 작업을 이해하는 데 도움이 될 스크린샷, 첨부파일, 링크 등 추가 정보를 작성해주세요. (선택 사항)

  - type: markdown
    attributes:
      value: |
        ---
        ### 이슈를 생성하기 전에 아래 내용을 확인해주세요:
        - 제목이 작업의 내용을 잘 표현하고 있습니다.
        - 작업자를 지정했습니다.
        - Label이 단 하나만 선택되어 있습니다.
        - 프로젝트를 연결했습니다.